name: 'UpperCampus ECS Deployment preparation action'
description: 'Performs preparation for ECS deployments to UpperCampus ECS clusters'
inputs:
  short-service:
    required: true
    description: "Short name of the service used as search string for AWS outputs"
  image:
    required: true
    description: "Docker image to put into the task definition files"
  stg-beta-ecs-task-definition-file:
    description: "Staging Beta ECS Task definition family filename"
    required: false
    default: task-definition-stg-beta.json
  prd-beta-ecs-task-definition-file:
    description: "Production Beta ECS Task definition family filename"
    required: false
    default: task-definition-prd-beta.json
outputs:
  stg-beta-ecs-cluster:
    description: "Staging-Beta ECS Cluster Name"
    value: ${{ steps.generate-task-definitions.outputs.stg-beta-ecs-cluster }}
  prd-beta-ecs-cluster:
    description: "Production-Beta ECS Cluster Name"
    value: ${{ steps.generate-task-definitions.outputs.prd-beta-ecs-cluster }}
  stg-beta-ecs-service:
    description: "Staging-Beta ECS Service Name"
    value: ${{ steps.generate-task-definitions.outputs.stg-beta-ecs-service }}
  prd-beta-ecs-service:
    description: "Production-Beta ECS Service Name"
    value: ${{ steps.generate-task-definitions.outputs.prd-beta-ecs-service }}
  stg-beta-ecs-task-definition-family:
    description: "Staging-Beta ECS Task definition family"
    value: ${{ steps.generate-task-definitions.outputs.stg-beta-ecs-task-definition-family }}
  prd-beta-ecs-task-definition-family:
    description: "Production-Beta ECS Task definition family"
    value: ${{ steps.generate-task-definitions.outputs.prd-beta-ecs-task-definition-family }}
  stg-beta-ecs-task-definition-file:
    description: "Name of the generated task definition file for staging-beta"
    value: ${{ inputs.stg-beta-ecs-task-definition-file }}
  prd-beta-ecs-task-definition-file:
    description: "Name of the generated task definition file for production-beta"
    value: ${{ inputs.prd-beta-ecs-task-definition-file }}

runs:
  using: "composite"
  steps:
    - id: generate-task-definitions
      name: Generate task definition files
      shell: bash
      run: |
        set -x

        # Parameter 1: stage
        determine_cluster () {
          echo $(aws ecs list-clusters --query clusterArns \
            | jq -r ".[] | select(. | contains(\"$1-ecs\"))" \
            | cut -d/ -f 2 \
            | uniq)
        }

        # Parameter 1: stage
        # Parameter 2: cluster
        determine_service () {
          echo $(aws ecs list-services --cluster $2 --query "serviceArns" \
            | jq -r ".[] | select(. | contains(\"$1-ecs\"))" \
            | cut -d/ -f 3 \
            | grep ${{ inputs.short-service }} \
            | uniq)
        }

        # Parameter 1: stage
        determine_task_definition () {
          echo $(aws ecs list-task-definitions --query "taskDefinitionArns" \
            | jq -r ".[] | select(. | contains(\"$1ecs\"))" \
            | cut -d/ -f 2 \
            | cut -d: -f 1 \
            | grep ${{ inputs.short-service }} \
            | uniq)
        }

        # Parameter 1: Output file name
        # Parameter 2: Task definition family
        create_task_definition () {
          aws ecs describe-task-definition --task-definition $2 --query taskDefinition \
            | jq ".containerDefinitions[0].image = \"${{ inputs.image }}\"" \
            > $1
        }

        STG_BETA_ECS_CLUSTER=$(determine_cluster stg-beta)
        echo "stg-beta-ecs-cluster=$(echo $STG_BETA_ECS_CLUSTER)" >> $GITHUB_OUTPUT

        STG_BETA_ECS_SERVICE=$(determine_service stg-beta ${STG_BETA_ECS_CLUSTER})
        echo "stg-beta-ecs-service=$(echo $STG_BETA_ECS_SERVICE)" >> $GITHUB_OUTPUT

        STG_BETA_TASK_DEFINITION_FAMILY=$(determine_task_definition stgbeta)
        echo "stg-beta-ecs-task-definition-family=$(echo $STG_BETA_TASK_DEFINITION_FAMILY)" >> $GITHUB_OUTPUT

        PRD_BETA_ECS_CLUSTER=$(determine_cluster prd-beta)
        echo "prd-beta-ecs-cluster=$(echo $PRD_BETA_ECS_CLUSTER)" >> $GITHUB_OUTPUT

        PRD_BETA_ECS_SERVICE=$(determine_service "prd-beta" ${PRD_BETA_ECS_CLUSTER})
        echo "prd-beta-ecs-service=$(echo $PRD_BETA_ECS_SERVICE)" >> $GITHUB_OUTPUT

        PRD_BETA_TASK_DEFINITION_FAMILY=$(determine_task_definition "prdbeta")
        echo "prd-beta-ecs-task-definition-family=$(echo $PRD_BETA_TASK_DEFINITION_FAMILY)" >> $GITHUB_OUTPUT

        create_task_definition ${{ inputs.stg-beta-ecs-task-definition-file }} $STG_BETA_TASK_DEFINITION_FAMILY
        create_task_definition ${{ inputs.prd-beta-ecs-task-definition-file }} $PRD_BETA_TASK_DEFINITION_FAMILY
